### ISSUE TITLE
Crash on mod loading

### ISSUE THREAD

**Issue by SGUDestiny** [mistersecret312/StoneMedusa#1]
### Mod version

stonemedusa-1.20.1-0.0.1

### Other mods

- [X] There are other mods present in the installation.

### Describe the issue

Log says something about mixins
[latest.log](https://github.com/user-attachments/files/17831313/latest.log)

### Required confirmation

- [X] I confirm that I have provided a log and this issue is not repeated.

**Comment by mistersecret312** [comment]
Potential conflict with other mods. Cant replicate.
